export const REQUEST_TENANT = 'REQUEST_TENANT'
export const REQUEST_TENANT_SUCCESS = 'REQUEST_TENANT_SUCCESS'
export const REQUEST_TENANT_FAILURE = 'REQUEST_TENANT_FAILURE'
export const REQUEST_TENANT_LOADING = 'REQUEST_TENANT_LOADING'

export const getTenant = () => ({
  type: REQUEST_TENANT,
})
